[package]
name = "h3o-server"
version = "0.1.0"
authors = ["MetaMuffin <metamuffin@yandex.com>"]
edition = "2018"

[dependencies]
tokio = { version = "0.2.22", features = ["full"] }
futures = "0.3.5"
regex = "1"
#lazy_static = "1.4"